
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjxcxgemdrcxyxnlbarp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqeGN4Z2VtZHJjeHl4bmxiYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjIwNjYsImV4cCI6MjA1ODEzODA2Nn0.CP7k8t1vpCWbkiweRRuUfVDQ6nnErOTgRioGCALTHig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
